### ISSUE TITLE
running problem ?

### ISSUE THREAD

**Issue by Suspectxyzz** [Decryptu/DecryptGPT#1]
hi I did everything but I get this one, do you have any idea what it could be from? I still need to download something separately

![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/50914568-e20e-4412-b7da-8b76c986074e)

**Comment by Decryptu** [comment]
Hello ! I think you are using the openai API v4 and not v3. I am going to update my bot so it works with v4, should be up today.

**Comment by Decryptu** [comment]
I've addressed this issue in the recent commit: [30e2976415f2b42073bfc2cfee83cd116bfa2b97](https://github.com/Decryptu/DecryptGPT/commit/30e2976415f2b42073bfc2cfee83cd116bfa2b97).

Dont forget to run "npm install" once before starting the bot !

**Comment by Suspectxyzz** [comment]
Hello, I downloaded the new version but I encountered another problem, what could it be?

```javascript
root@ubuntu:/home/bot# npm start

> decryptgpt@3.0.0 start
> node index.js

/home/bot/node_modules/@discordjs/ws/dist/index.js:1132
          error: new Error("Used disallowed intents")
                 ^

Error: Used disallowed intents
    at WebSocketShard.onClose (/home/bot/node_modules/@discordjs/ws/dist/index.js:1132:18)
    at connection.onclose (/home/bot/node_modules/@discordjs/ws/dist/index.js:676:17)
    at callListener (/home/bot/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/bot/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/home/bot/node_modules/ws/lib/websocket.js:260:10)
    at TLSSocket.socketOnClose (/home/bot/node_modules/ws/lib/websocket.js:1272:15)
    at TLSSocket.emit (node:events:525:35)
    at node:net:321:12
    at TCP.done (node:_tls_wrap:588:7)

``` 

![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/a52d3fca-fa1e-4e56-9862-d61fabe22e34)

**Comment by Decryptu** [comment]
In your discord bot config, did you gave him the authorisation for the intents ?

<img width="1440" alt="Capture d’écran 2024-01-02 à 12 51 58" src="https://github.com/Decryptu/DecryptGPT/assets/90518536/d7492e86-dc25-4b83-9f2d-b1fb6072d3ff">

**Comment by Suspectxyzz** [comment]
> In your discord bot config, did you gave him the authorisation for the intents ?
> 
> <img alt="Capture d’écran 2024-01-02 à 12 51 58" width="1440" src="https://private-user-images.githubusercontent.com/90518536/293685998-d7492e86-dc25-4b83-9f2d-b1fb6072d3ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTg0MjAsIm5iZiI6MTcwNDE5ODEyMCwicGF0aCI6Ii85MDUxODUzNi8yOTM2ODU5OTgtZDc0OTJlODYtZGMyNS00YjgzLTlmMmQtYjFmYjYwNzJkM2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiN2U0ZjJkNGU1YjUzNTdiYzUwNTkzZDlmYzY5NTVhMWYxNjA2MDYzNzAwOGQzNGViZTVlYTNmYmM4ZmI4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r2XfS-3kiBpUP1E5bNttqG8kdJ1HjRBIibfTVSaLAPI">

![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/6d4a0fa2-cab6-40f9-9d91-ce7feec53615)
it works but when generating images I get this
```javascript

Commands set successfully
Received /image command with description: vreau o pisica in spatiu astonaut
Error handling command image: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/bot/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/bot/node_modules/@discordjs/rest/dist/index.js:826:23)
    at async _REST.request (/home/bot/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async ChatInputCommandInteraction.deferReply (/home/bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
    at async dalle (file:///home/bot/commands/dalle.js:21:5)
    at async interactionCreate (file:///home/bot/events/interactionCreate.js:20:7) {
  requestBody: { files: undefined, json: { type: 5, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'xxxxxx'
}
node:events:491
      throw er; // Unhandled 'error' event
      ^

DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/bot/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/bot/node_modules/@discordjs/rest/dist/index.js:826:23)
    at async _REST.request (/home/bot/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async ChatInputCommandInteraction.reply (/home/bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async interactionCreate (file:///home/bot/events/interactionCreate.js:24:7)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: 'Sorry, there was an error processing your command.',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: 64,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'xxxxxxx'
}

Node.js v18.13.0
``` 
nothing works with nothing /
![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/6fc9dfd0-5ed7-4674-bca3-461f2bed6923)

**Comment by Decryptu** [comment]
Ok, I needed to migrate DALL-E to openai API v4 too, this one is fixed in the latest commit.
I'm working on the slash commands, should be fixed soon too.

**Comment by Decryptu** [comment]
Ok, fixed the slash commands in last commit, everything should be up and running with the latest openai API version.
<img width="886" alt="Capture d’écran 2024-01-02 à 14 06 57" src="https://github.com/Decryptu/DecryptGPT/assets/90518536/e0ae2e60-1bf9-49d4-86f6-67bc3b48da52">

**Comment by Suspectxyzz** [comment]
Same for me GPT-4 model & GPT-3 model 

try with my api key **add me in discord I can't put it because it automatically gets disable ") (leak protect)** suspectxyz /305021270003548161

![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/a473687b-75a3-4fa4-950f-3a40f160767d)
![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/e3b2f5ef-d644-4b86-b3a1-8ed75245be07)
```javascript
root@ubuntu:/home/bot# npm start

> decryptgpt@3.0.0 start
> node index.js

Edgar is online!
Commands set successfully
Switching to GPT-4 model for user: suspectxyz

Error handling command image: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/bot/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/bot/node_modules/@discordjs/rest/dist/index.js:826:23)
    at async _REST.request (/home/bot/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async ChatInputCommandInteraction.deferReply (/home/bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
    at async dalle (file:///home/bot/commands/dalle.js:16:5)
    at async interactionCreate (file:///home/bot/events/interactionCreate.js:20:7) {
  requestBody: { files: undefined, json: { type: 5, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: ''
}
node:events:491
      throw er; // Unhandled 'error' event
      ^

DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/bot/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/bot/node_modules/@discordjs/rest/dist/index.js:826:23)
    at async _REST.request (/home/bot/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async ChatInputCommandInteraction.reply (/home/bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async interactionCreate (file:///home/bot/events/interactionCreate.js:24:7)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: 'Sorry, there was an error processing your command.',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: 64,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: ''
}

Node.js v18.13.0

```

**Comment by Decryptu** [comment]
The error DiscordAPIError[10062]: Unknown interaction typically occurs in Discord bots when there's an issue with handling interactions, particularly with command responses. I'll need to investigate further for this one. You can try to clean the node folders and redo a "npm install" to ensure you are using the good dependencies versions, but I will try to fix this error anyway.

**Comment by Decryptu** [comment]
Just pushed a commit that could fix the timeout issue you were experiencing with the /gpt3 and /gpt4 commands. I've implemented asynchronous handling for the setBotActivity function to avoid blocking the interaction responses. Give it a try and let me know if it sorts things out!

**Comment by Suspectxyzz** [comment]
> Just pushed a commit that could fix the timeout issue you were experiencing with the /gpt3 and /gpt4 commands. I've implemented asynchronous handling for the setBotActivity function to avoid blocking the interaction responses. Give it a try and let me know if it sorts things out!

![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/31b4caa6-0140-4198-bc91-82d2166fafb6)
![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/9c926d90-fd57-4ecf-b4b6-f30b4f8fc9dd)
```javascript
Error in createDallEImage: BadRequestError: 400 Billing hard limit has been reached
    at APIError.generate (file:///C:/Users/Root/Desktop/DecryptGPT-main/node_modules/openai/error.mjs:40:20)
    at OpenAI.makeStatusError (file:///C:/Users/Root/Desktop/DecryptGPT-main/node_modules/openai/core.mjs:244:25)
    at OpenAI.makeRequest (file:///C:/Users/Root/Desktop/DecryptGPT-main/node_modules/openai/core.mjs:283:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createDallEImage (file:///C:/Users/Root/Desktop/DecryptGPT-main/utils/createDallEImage.js:5:26)
    at async dalle (file:///C:/Users/Root/Desktop/DecryptGPT-main/commands/dalle.js:19:26)
    at async interactionCreate (file:///C:/Users/Root/Desktop/DecryptGPT-main/events/interactionCreate.js:20:7) {
  status: 400,
  headers: {
    'access-control-allow-origin': '*',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '83f420fd38242866-OTP',
    connection: 'keep-alive',
    'content-length': '172',
    'content-type': 'application/json',
    date: 'Tue, 02 Jan 2024 15:45:24 GMT',
    'openai-organization': 'user-lyzjilqsksxnrfdu7i0zc0py',
    'openai-processing-ms': '99',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=xxxxx; path=/; expires=Tue, 02-Jan-24 16:15:24 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=iZyx5jpEriiwt4twtolE6L_tzTjRYOsu1wzoCfL0jNs-1704210324332-0-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'x-request-id': 'c5d1d3f117014472a33d3e51413a3025'
  },
  error: {
    code: 'billing_hard_limit_reached',
    message: 'Billing hard limit has been reached',
    param: null,
    type: 'invalid_request_error'
  },
  code: 'billing_hard_limit_reached',
  param: null,
  type: 'invalid_request_error'
}
Error in dalle function: BadRequestError: 400 Billing hard limit has been reached
    at APIError.generate (file:///C:/Users/Root/Desktop/DecryptGPT-main/node_modules/openai/error.mjs:40:20)
    at OpenAI.makeStatusError (file:///C:/Users/Root/Desktop/DecryptGPT-main/node_modules/openai/core.mjs:244:25)
    at OpenAI.makeRequest (file:///C:/Users/Root/Desktop/DecryptGPT-main/node_modules/openai/core.mjs:283:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createDallEImage (file:///C:/Users/Root/Desktop/DecryptGPT-main/utils/createDallEImage.js:5:26)
    at async dalle (file:///C:/Users/Root/Desktop/DecryptGPT-main/commands/dalle.js:19:26)
    at async interactionCreate (file:///C:/Users/Root/Desktop/DecryptGPT-main/events/interactionCreate.js:20:7) {
  status: 400,
  headers: {
    'access-control-allow-origin': '*',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '83f420fd38242866-OTP',
    connection: 'keep-alive',
    'content-length': '172',
    'content-type': 'application/json',
    date: 'Tue, 02 Jan 2024 15:45:24 GMT',
    'openai-organization': 'user-lyzjilqsksxnrfdu7i0zc0py',
    'openai-processing-ms': '99',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=xxxxxxxxx HttpOnly; Secure; SameSite=None, _cfuvid=iZyx5jpEriiwt4twtolE6L_tzTjRYOsu1wzoCfL0jNs-1704210324332-0-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'x-request-id': 'xxxxxx'
  },
  error: {
    code: 'billing_hard_limit_reached',
    message: 'Billing hard limit has been reached',
    param: null,
    type: 'invalid_request_error'
  },
  code: 'billing_hard_limit_reached',
  param: null,
  type: 'invalid_request_error'
}
```

**Comment by Decryptu** [comment]
Oh and I noticed you are using Node.js v18.13.0
Try with v20.10.0 at least. It could solve the problem.

**Comment by Decryptu** [comment]
Oh you just reached the openai API limit.

**Comment by Suspectxyzz** [comment]
> Oh and I noticed you are using Node.js v18.13.0 Try with v20.10.0 at least. It could solve the problem.

i try in my pc
![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/c33104ff-2f56-4b7c-b43e-e5e8a08eeea0)

**Comment by Decryptu** [comment]
You don't have any more credits on your openai account : 

```
  error: {
    code: 'billing_hard_limit_reached',
    message: 'Billing hard limit has been reached',
    param: null,
    type: 'invalid_request_error'
  },
  code: 'billing_hard_limit_reached',
  param: null,
  type: 'invalid_request_error'
}
```

**Comment by Suspectxyzz** [comment]
> Oh you just reached the openai API limit.

simple chat doesn't work either model 3/4 

> You don't have any more credits on your openai account :
> 
> ```
>   error: {
>     code: 'billing_hard_limit_reached',
>     message: 'Billing hard limit has been reached',
>     param: null,
>     type: 'invalid_request_error'
>   },
>   code: 'billing_hard_limit_reached',
>   param: null,
>   type: 'invalid_request_error'
> }
> ```

it works in the browser

**Comment by Decryptu** [comment]
ChatGPT in browser and the openai API are not using the same billing. Its separate.
Check your usage here : https://platform.openai.com/account/usage

**Comment by Suspectxyzz** [comment]
> ChatGPT in browser and the openai API are not using the same billing. Its separate.

but it doesn't work in chat either ?

**Comment by Decryptu** [comment]
> > ChatGPT in browser and the openai API are not using the same billing. Its separate.
> 
> but it doesn't work in chat either ?

the API uses the same billing for all the type of requests, dalle, gpt3, gpt4. But if you use the browser version it will use a different billing.

**Comment by Decryptu** [comment]
also the /gpt3 and /gpt4 commands are only here to switch between models, once the bot is using a model, you dont need to use slash commands to talk with him, he will read all the messages in the discord chat. You can talk like you talk to a normal person.

**Comment by Suspectxyzz** [comment]
> also the /gpt3 and /gpt4 commands are only here to switch between models, once the bot is using a model, you dont need to use slash commands to talk with him, he will read all the messages in the discord chat. You can talk like you talk to a normal person.

![image](https://github.com/Decryptu/DecryptGPT/assets/45514952/c6f1c8b7-70d7-434f-bf65-eab0b3525a72)
nah

**Comment by Decryptu** [comment]
Are you sure he has access to this channel ? I pushed a commit to add some logs to print the messages he can read in the console, if the console is empty, it might be because he is missing some rights, like read access.

<img width="205" alt="Capture d’écran 2024-01-02 à 17 03 04" src="https://github.com/Decryptu/DecryptGPT/assets/90518536/f6de5a2c-0e18-4ef2-9675-1f5d8217001b">

**Comment by Suspectxyzz** [comment]
it works now yes, but as you say it is limited. Rate limit reached for requests !
&
can you add a message on discord to tell the bot when it has reached the limit?

**Comment by Decryptu** [comment]
Ok thank you for the feedback ! I will try to add it today !

**Comment by Decryptu** [comment]
Fixed in last commit : 

<img width="770" alt="Capture d’écran 2024-01-03 à 14 13 25" src="https://github.com/Decryptu/DecryptGPT/assets/90518536/b1e75ad9-3c90-4f02-9931-786e46969747">
